export const copy = {
  cliMissing: (agent: string) =>
    `${agent} CLI not found. Plugin install and enable need it. Skill toggles still work.`,
  cliTooOld: (agent: string) => `${agent} CLI is too old for plugin commands.`,
  emptyPlugins: "No plugins on this circuit.",
  emptyUserSkills: "No user skills.",
  emptyMcps: "No MCP servers on this circuit.",
  cursorMcpReadOnly:
    "Cursor keeps MCP servers on or off in its own settings, so on-n-off lists them but cannot switch them here. Manage them in the Cursor app, or run `agent mcp enable <name>` / `agent mcp disable <name>`.",
  filterMiss: (q: string) => `Nothing matches “${q}”.`,
  skillLocked: "Claude only enables this with the whole plugin.",
  skillProject: "Local to this project. Presence is on; no disable yet.",
  driftTitle: "Out of sync with upstream",
  upToDate: "up to date",
  folderUnsupported: "This agent’s CLI can’t install from a folder.",
  parseError: (path: string, error: string) => `Couldn’t read ${path}. ${error}`,
  writeRollback: "Write failed. Restored the previous file.",
  uninstallTitle: (name: string) => `Uninstall “${name}”?`,
  uninstallBody: (agent: string) =>
    `Removes it from ${agent}. This does not delete your backup.`,
  installHelper: "HTTPS git, owner/repo, name@marketplace, or npx skills add. SSH later.",
  installInvalid: "Use an HTTPS git URL, owner/repo, name@marketplace, or npx skills add.",
  filterPlaceholder: "plugins, skills, mcps…",
  refresh: "Refresh",
  install: "Install",
  installing: "Installing…",
  folder: "Choose folder…",
  cancel: "Cancel",
  uninstall: "Uninstall",
  update: "Update",
} as const;
