export const copy = {
  cliMissing: (agent: string) =>
    `${agent} CLI not found. Plugin install and enable need it. Skill toggles still work.`,
  cliTooOld: (agent: string) => `${agent} CLI is too old for plugin commands.`,
  emptyPlugins: "No plugins on this circuit.",
  emptyUserSkills: "No user skills.",
  emptyMcps: "No MCP servers on this circuit.",
  cursorMcpReadOnly:
    "Cursor keeps MCP servers on or off in its own settings, so on-n-off lists them but cannot switch them here. Manage them in the Cursor app, or run `agent mcp enable <name>` / `agent mcp disable <name>`.",
  filterMiss: (q: string) => `Nothing matches “${q}”.`,
  skillLocked: "Claude only enables this with the whole plugin.",
  skillProject: "Local to this project. Presence is on; no disable yet.",
  driftTitle: "Out of sync with upstream",
  upToDate: "up to date",
  folderUnsupported: "This agent’s CLI can’t install from a folder.",
  parseError: (path: string, error: string) => `Couldn’t read ${path}. ${error}`,
  writeRollback: "Write failed. Restored the previous file.",
  uninstallTitle: (name: string) => `Uninstall “${name}”?`,
  uninstallBody: (agent: string) =>
    `Removes it from ${agent}. This does not delete your backup.`,
  installHelper: "HTTPS git, owner/repo, name@marketplace, or npx skills add. SSH later.",
  installInvalid: "Use an HTTPS git URL, owner/repo, name@marketplace, or npx skills add.",
  filterPlaceholder: "plugins, skills, mcps…",
  refresh: "Refresh",
  install: "Install",
  installing: "Installing…",
  folder: "Choose folder…",
  cancel: "Cancel",
  uninstall: "Uninstall",
  update: "Update",
  marketplaceLoading: "Reading the marketplace…",
  marketplaceNotFound:
    "No plugin marketplace in this repository. You can still add it with the plugin option.",
  marketplaceFailed: (error: string) => `Couldn’t download the marketplace. ${error}`,
  actionPlugin: "Install plugin",
  actionPluginHint: "Register the marketplace with the CLI; you enable plugins from Plugins.",
  actionAll: "Install everything as local skills/agents",
  actionAllHint: "Copies every skill and agent into the providers below. Tracked for updates.",
  actionSelected: "Install selected skills/agents",
  actionSelectedHint: "Pick the ones you want. Tracked for updates.",
  installItemsButton: (count: number) => (count === 1 ? "Install 1 item" : `Install ${count} items`),
  targetsProviders: "PROVIDERS",
  targetsScope: "SCOPE",
  scopeGlobal: "Global",
  scopeProject: "Project",
  claudeOnly: "Claude only",
  agentsNeedClaude: "Subagents only install into Claude — add Claude as a provider.",
  selectAll: "all",
  selectNone: "none",
  unsupportedPlugin: "on-n-off can’t fetch this plugin’s source; use Install plugin instead.",
  shaMoved: "Upstream moved while you were choosing; installed the newest commit.",
  overwriteConflicts: (count: number) =>
    count === 1 ? "Overwrite this one?" : `Overwrite these ${count}?`,
  conflictHint: "Already present and not installed by on-n-off. A backup is kept if you overwrite.",
  itemInstalled: "installed",
  itemReplaced: "replaced",
  itemSkipped: "skipped",
  itemConflict: "conflict",
  itemFailed: "failed",
  itemsDone: (count: number, providers: number) =>
    `${count} item${count === 1 ? "" : "s"} installed across ${providers} provider${providers === 1 ? "" : "s"}.`,
  updateAvailable: (version: string) => `update available → ${version}`,
  modifiedLocally: "modified locally",
  itemMissing: "missing on disk",
  checkUpdates: "Check for updates",
  removeItem: "Remove",
  keepMine: "Keep mine",
  overwriteBackup: "Overwrite (backup kept)",
  updateItemTitle: (name: string) => `Update “${name}”?`,
  updateItemBody: (version: string) =>
    `Upstream has ${version}. Overwrite replaces your copy (a backup is kept). Keep mine hides this version until the next one.`,
  updateItemBodyModified: (version: string) =>
    `Upstream has ${version} and your copy is modified locally. Overwrite replaces it (a backup is kept). Keep mine hides this version until the next one.`,
  removeItemTitle: (name: string) => `Remove “${name}”?`,
  removeItemBody: "Deletes the local copy (a backup is kept) and stops tracking it.",
  agentsSection: "Subagents",
} as const;
